### PR TITLE
RuboCop: include cop names in annotation messages

### LINKED ISSUE #21: Output cops in RuboCop annotations
Hello.

I see annotations like this:

image

But I don't see cop names there.

For example, regular CLI output:

```
> toys rubocop
[2020-09-08 20:45:56   ANY]  ["rubocop", "rubocop"]
Inspecting 13 files
....C...W....

Offenses:

exe/compile/_base_command.rb:22:10: C: Style/SoleNestedConditional: Consider merging nested conditions into outer unless conditions.
			abort unless system 'toys config check'
         ^^^^^^
exe/compile/pages_command.rb:89:4: W: Lint/UselessMethodDefinition: Useless method definition detected.
			def render_partial(file_name, base_dir: PAGES_TEMPLATES_DIR, **options) ...
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

13 files inspected, 2 offenses detected, 2 offenses auto-correctable
```

So, there are `Style/SoleNestedConditional` and `Lint/UselessMethodDefinition`. And they're important: for example, to check changelog for them. Or I can have [a PR with additional gem update, `rubocop-performance`](https://github.com/AlexWayfer/alexwayfer.name/pull/21), and it has its own namespace, `Performance/`, and I want to know if I have errors from this add-on or there are errors from a new `rubocop` version (or errors with CI strategy, like [it was actually](https://github.com/AlexWayfer/alexwayfer.name/pull/23)).

So, please, output somewhere a cop name, for example before offense text, like it's in CLI.

I've checked, there are cop names in JSON output:

```json
{
	"metadata": {
		"rubocop_version": "0.90.0",
		"ruby_engine": "ruby",
		"ruby_version": "2.7.1",
		"ruby_patchlevel": "83",
		"ruby_platform": "x86_64-linux"
	},
	"files": [{
		"path": ".toys.rb",
		"offenses": []
	}, {
		"path": "Gemfile",
		"offenses": []
	}, {
		"path": "exe/_bundler_setup.rb",
		"offenses": []
	}, {
		"path": "exe/compile.rb",
		"offenses": []
	}, {
		"path": "exe/compile/_base_command.rb",
		"offenses": [{
			"severity": "convention",
			"message": "Style/SoleNestedConditional: Consider merging nested conditions into outer `unless` conditions.",
			"cop_name": "Style/SoleNestedConditional",
			"corrected": false,
			"correctable": true,
			"location": {
				"start_line": 22,
				"start_column": 10,
				"last_line": 22,
				"last_column": 15,
				"length": 6,
				"line": 22,
				"column": 10
			}
		}]
	}, {
		"path": "exe/compile/all_command.rb",
		"offenses": []
	}, {
		"path": "exe/compile/assets_command.rb",
		"offenses": []
	}, {
		"path": "exe/compile/data.rb",
		"offenses": []
	}, {
		"path": "exe/compile/pages_command.rb",
		"offenses": [{
			"severity": "warning",
			"message": "Lint/UselessMethodDefinition: Useless method definition detected.",
			"cop_name": "Lint/UselessMethodDefinition",
			"corrected": false,
			"correctable": true,
			"location": {
				"start_line": 89,
				"start_column": 4,
				"last_line": 91,
				"last_column": 6,
				"length": 88,
				"line": 89,
				"column": 4
			}
		}]
	}, {
		"path": "exe/compile/pdf_command.rb",
		"offenses": []
	}, {
		"path": "exe/compile/view_object.rb",
		"offenses": []
	}, {
		"path": "exe/deploy.rb",
		"offenses": []
	}, {
		"path": "extra/deploy_api.rb",
		"offenses": []
	}],
	"summary": {
		"offense_count": 2,
		"target_file_count": 13,
		"inspected_file_count": 13
	}
}
```

### PR DESCRIPTION
**Pull request by edigaryev**
Resolves #21.

### CODE REVIEW

**Review by fkorotkov — APPROVED** [review]
That was quick! 😲

**Comment by AlexWayfer** [comment]
To be honest, as I see in a JSON output, `message` field contains cop's name. Can you please explain me details about implementation (shortly)? Or maybe you did something wrong basically. Quote:

```json
		"offenses": [{
			"severity": "convention",
			"message": "Style/SoleNestedConditional: Consider merging nested conditions into outer `unless` conditions.",
			"cop_name": "Style/SoleNestedConditional",
			"corrected": false,
			"correctable": true,
			"location": {
				"start_line": 22,
				"start_column": 10,
				"last_line": 22,
				"last_column": 15,
				"length": 6,
				"line": 22,
				"column": 10
			}
		}]
```

So, I don't see a message without a cop's name, but I see a message **with** a cop's name and separately a cop's name without a message.

Your changes look like you've added a cop's name to a message, and it resolves the issue, I think, but why there is a message without a cop's name at all?

**Comment by AlexWayfer** [comment]
> That was quick!

I agree, thank you.

**Comment by edigaryev** [comment]
> To be honest, as I see in a JSON output, `message` field contains cop's name.

This seems to be related to https://github.com/rubocop-hq/rubocop/pull/6924 change and was introduced in [RuboCop 0.68.0](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md#0680-2019-04-29).

Is it possible that when you run RuboCop locally it has a version less than that is installed in the CI (less than `0.68.0` to be exact)?

**Comment by edigaryev** [comment]
There was also a change (https://github.com/rubocop-hq/rubocop/pull/5037) in [RuboCop 0.52.0](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md#0520-2017-12-12) regarding cop names that enabled them globally. Then the fix from the message above came in and reverted the initial state to that of observed in `0.50.0` by disabling cop names, but only in JSON `message` fields.

However, this all seems to be unrelated since you're running `0.90.0` and still getting cop names in messages.

**Comment by AlexWayfer** [comment]
> This seems to be related to [rubocop-hq/rubocop#6924](https://github.com/rubocop-hq/rubocop/pull/6924) change and was introduced in [RuboCop 0.68.0](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md#0680-2019-04-29).

Interesting.



> Is it possible that when you run RuboCop locally it has a version less than that is installed in the CI (less than `0.68.0` to be exact)?

Seems no:


```
> toys rubocop --format=json
[2020-09-09 01:56:27   ANY]  ["rubocop", "--format=json"]
{"metadata":{"rubocop_version":"0.90.0","ruby_engine":"ruby","ruby_version":"2.7.1","ruby_patchlevel":"83","ruby_platform":"x86_64-linux"},"files":[{"path":".toys.rb","offenses":[]},{"path":"Gemfile","offenses":[]},{"path":"exe/_bundler_setup.rb","offenses":[]},{"path":"exe/compile.rb","offenses":[]},{"path":"exe/compile/_base_command.rb","offenses":[{"severity":"convention","message":"Style/SoleNestedConditional: Consider merging nested conditions into outer `unless` conditions.","cop_name":"Style/SoleNestedConditional","corrected":false,"correctable":true,"location":{"start_line":22,"start_column":10,"last_line":22,"last_column":15,"length":6,"line":22,"column":10}}]},{"path":"exe/compile/all_command.rb","offenses":[]},{"path":"exe/compile/assets_command.rb","offenses":[]},{"path":"exe/compile/data.rb","offenses":[]},{"path":"exe/compile/pages_command.rb","offenses":[{"severity":"warning","message":"Lint/UselessMethodDefinition: Useless method definition detected.","cop_name":"Lint/UselessMethodDefinition","corrected":false,"correctable":true,"location":{"start_line":89,"start_column":4,"last_line":91,"last_column":6,"length":88,"line":89,"column":4}}]},{"path":"exe/compile/pdf_command.rb","offenses":[]},{"path":"exe/compile/view_object.rb","offenses":[]},{"path":"exe/deploy.rb","offenses":[]},{"path":"extra/deploy_api.rb","offenses":[]}],"summary":{"offense_count":2,"target_file_count":13,"inspected_file_count":13}}

> toys rubocop -V
[2020-09-09 01:56:37   ANY]  ["rubocop", "-V"]
0.90.0 (using Parser 2.7.1.4, rubocop-ast 0.3.0, running on ruby 2.7.1 x86_64-linux)
```

We can not complicate it via `toys`, so let's use simple `bundle exec`:

```
> bundle exec rubocop -V
0.90.0 (using Parser 2.7.1.4, rubocop-ast 0.3.0, running on ruby 2.7.1 x86_64-linux)

> bundle exec rubocop --format=json
{"metadata":{"rubocop_version":"0.90.0","ruby_engine":"ruby","ruby_version":"2.7.1","ruby_patchlevel":"83","ruby_platform":"x86_64-linux"},"files":[{"path":".toys.rb","offenses":[]},{"path":"Gemfile","offenses":[]},{"path":"exe/_bundler_setup.rb","offenses":[]},{"path":"exe/compile.rb","offenses":[]},{"path":"exe/compile/_base_command.rb","offenses":[{"severity":"convention","message":"Style/SoleNestedConditional: Consider merging nested conditions into outer `unless` conditions.","cop_name":"Style/SoleNestedConditional","corrected":false,"correctable":true,"location":{"start_line":22,"start_column":10,"last_line":22,"last_column":15,"length":6,"line":22,"column":10}}]},{"path":"exe/compile/all_command.rb","offenses":[]},{"path":"exe/compile/assets_command.rb","offenses":[]},{"path":"exe/compile/data.rb","offenses":[]},{"path":"exe/compile/pages_command.rb","offenses":[{"severity":"warning","message":"Lint/UselessMethodDefinition: Useless method definition detected.","cop_name":"Lint/UselessMethodDefinition","corrected":false,"correctable":true,"location":{"start_line":89,"start_column":4,"last_line":91,"last_column":6,"length":88,"line":89,"column":4}}]},{"path":"exe/compile/pdf_command.rb","offenses":[]},{"path":"exe/compile/view_object.rb","offenses":[]},{"path":"exe/deploy.rb","offenses":[]},{"path":"extra/deploy_api.rb","offenses":[]}],"summary":{"offense_count":2,"target_file_count":13,"inspected_file_count":13}}
```

The same. So, I see cop's names in the `message` property. You can check it locally at this repository and commit: https://github.com/AlexWayfer/alexwayfer.name/commit/a44ab0a46e2b3908b73afea1eba5f05c47e8c2d2

**Comment by edigaryev** [comment]
> The same. So, I see cop's names in the `message` property. You can check it locally at this repository and commit: [AlexWayfer/alexwayfer.name@a44ab0a](https://github.com/AlexWayfer/alexwayfer.name/commit/a44ab0a46e2b3908b73afea1eba5f05c47e8c2d2)

Unfortunately, I can't seem to reproduce this locally by running [`cirrus run -v rubocop`](https://github.com/cirruslabs/cirrus-cli) against the commit above with the following `.cirrus.yml` changes:

```diff
diff --git a/.cirrus.yml b/.cirrus.yml
index eb4b194..56e5fba 100644
--- a/.cirrus.yml
+++ b/.cirrus.yml
@@ -61,7 +61,7 @@ rubocop_task:
     image: ruby:latest
   <<: *bundle_cache
 
-  lint_script: toys rubocop --format=json --out=rubocop.json
+  lint_script: toys rubocop --format=json
 
   always:
     rubocop_artifacts:
```

The resulting JSON does not contain the extra cop names like the yours does:

```json
{
  "metadata": {
    "rubocop_version": "0.90.0",
    "ruby_engine": "ruby",
    "ruby_version": "2.7.1",
    "ruby_patchlevel": "83",
    "ruby_platform": "x86_64-linux"
  },
  "files": [
    {
      "path": ".toys.rb",
      "offenses": []
    },
    {
      "path": "Gemfile",
      "offenses": []
    },
    {
      "path": "exe/_bundler_setup.rb",
      "offenses": []
    },
    {
      "path": "exe/compile.rb",
      "offenses": []
    },
    {
      "path": "exe/compile/_base_command.rb",
      "offenses": [
        {
          "severity": "convention",
          "message": "Consider merging nested conditions into outer `unless` conditions.",
          "cop_name": "Style/SoleNestedConditional",
          "corrected": false,
          "correctable": false,
          "location": {
            "start_line": 22,
            "start_column": 10,
            "last_line": 22,
            "last_column": 15,
            "length": 6,
            "line": 22,
            "column": 10
          }
        }
      ]
    },
    {
      "path": "exe/compile/all_command.rb",
      "offenses": []
    },
    {
      "path": "exe/compile/assets_command.rb",
      "offenses": []
    },
    {
      "path": "exe/compile/data.rb",
      "offenses": []
    },
    {
      "path": "exe/compile/pages_command.rb",
      "offenses": [
        {
          "severity": "warning",
          "message": "Useless method definition detected.",
          "cop_name": "Lint/UselessMethodDefinition",
          "corrected": false,
          "correctable": true,
          "location": {
            "start_line": 89,
            "start_column": 4,
            "last_line": 91,
            "last_column": 6,
            "length": 88,
            "line": 89,
            "column": 4
          }
        }
      ]
    },
    {
      "path": "exe/compile/pdf_command.rb",
      "offenses": []
    },
    {
      "path": "exe/compile/view_object.rb",
      "offenses": []
    },
    {
      "path": "exe/deploy.rb",
      "offenses": []
    }
  ],
  "summary": {
    "offense_count": 2,
    "target_file_count": 12,
    "inspected_file_count": 12
  }
}
```

Is it possible that you have a RuboCop config [in one of these locations](https://docs.rubocop.org/rubocop/configuration.html#config-file-locations) with some non-default options set?

**Comment by AlexWayfer** [comment]
> Is it possible that you have a RuboCop config [in one of these locations](https://docs.rubocop.org/rubocop/configuration.html#config-file-locations) with some non-default options set?

No, I've checked. The only one RuboCop's config is in repository root directory. Also I don't remember any configuration options for such difference in output.

---

I want to try `cirrus run -v rubocop`, but right now I'm stuck with https://github.com/cirruslabs/cirrus-cli/issues/71. Let's wait.

**Comment by AlexWayfer** [comment]
> I want to try `cirrus run -v rubocop`, but right now I'm stuck with [cirruslabs/cirrus-cli#71](https://github.com/cirruslabs/cirrus-cli/issues/71). Let's wait.

It was resolved, now I'm facing with https://github.com/cirruslabs/cirrus-cli/issues/74.

**Comment by AlexWayfer** [comment]
> > I want to try `cirrus run -v rubocop`, but right now I'm stuck with [cirruslabs/cirrus-cli#71](https://github.com/cirruslabs/cirrus-cli/issues/71). Let's wait.
> 
> It was resolved, now I'm facing with [cirruslabs/cirrus-cli#74](https://github.com/cirruslabs/cirrus-cli/issues/74).

I've used `sudo` and I'm getting:

```
> sudo cirrus run -v rubocop
[sudo] password for alex: 
gRPC server is listening at http://172.17.0.1:41183
running task rubocop (3)
Started 'rubocop'
Started 'Preparing execution environment...'
Preparing volume to work with...
'Preparing execution environment...' succeeded in 4.4s!
creating Docker client
creating container using working volume d19620a9cb0195b63884082b2e585ab227848beb9fcc6b360115325abc119e5a
starting container 08a0722b78b85512e637e6c3a8ba4ef5acf1a6a81555ad9548c013fabe86792a
waiting for container 08a0722b78b85512e637e6c3a8ba4ef5acf1a6a81555ad9548c013fabe86792a to finish
agent signal: urgent I/O condition
received heartbeat
received heartbeat
Started 'bundle'
begin streaming logs
received log chunk of 30 bytes
echo $CIRRUS_OS
linux
ruby -v

received log chunk of 57 bytes
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]

received log chunk of 17 bytes
cat Gemfile.lock

received log chunk of 1947 bytes
GIT
  remote: https://github.com/excpt/moments.git
  revision: 04d2f5e87c9ed4ae4c25111cb226b7e5cde3ed30
  specs:
    moments (0.1.0.alpha)

GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.7.0)
      public_suffix (>= 2.0.2, < 5.0)
    alt_memery (2.0.0)
      module_methods (~> 0.1.0)
      ruby2_keywords (~> 0.0.2)
    ast (2.4.1)
    clamp (1.3.1)
    cliver (0.3.2)
    concurrent-ruby (1.1.7)
    config_toys (0.2.0)
      example_file (~> 0.1.0)
      toys-core (~> 0.11.0)
    diffy (3.4.0)
    example_file (0.1.0)
      diffy (~> 3.0)
      highline (~> 2.0)
      paint (~> 2.0)
    ferrum (0.9)
      addressable (~> 2.5)
      cliver (~> 0.3)
      concurrent-ruby (~> 1.1)
      websocket-driver (>= 0.6, < 0.8)
    gorilla_patch (2.9.1)
    highline (2.0.3)
    icomoon_toys (0.2.0)
      alt_memery (~> 2.0)
      rubyzip (~> 2.0)
      toys-core (~> 0.11.0)
    kramdown (2.3.0)
      rexml
    module_methods (0.1.0)
    paint (2.2.0)
    parallel (1.19.2)
    parser (2.7.1.4)
      ast (~> 2.4.1)
    public_suffix (4.0.5)
    rainbow (3.0.0)
    regexp_parser (1.7.1)
    rexml (3.2.4)
    rubocop (0.90.0)
      parallel (~> 1.10)
      parser (>= 2.7.1.1)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.7)
      rexml
      rubocop-ast (>= 0.3.0, < 1.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 1.4.0, < 2.0)
    rubocop-ast (0.3.0)
      parser (>= 2.7.1.4)
    rubocop-performance (1.7.1)
      rubocop (>= 0.82.0)
    ruby-progressbar (1.10.1)
    ruby2_keywords (0.0.2)
    rubyzip (2.3.0)
    toys (0.11.1)
      toys-core (= 0.11.1)
    toys-core (0.11.1)
    unicode-display_width (1.7.0)
    websocket-driver (0.7.3)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)

PLATFORMS
  ruby

DEPENDENCIES
  clamp
  config_toys
  ferrum
  gorilla_patch
  icomoon_toys
  kramdown
  moments!
  rubocop
  rubocop-performance
  toys

BUNDLED WITH
   2.1.4

error while getting cache blob with key bundle-b5110ff6c6df20cf28d023f6c3d1e82ff20b126e58a079e261ad66cd2e2639fd: blob with the specified key not found
received log chunk of 116 bytes

Cache miss for bundle-b5110ff6c6df20cf28d023f6c3d1e82ff20b126e58a079e261ad66cd2e2639fd! No script to populate with.
command succeeded
'bundle' succeeded in 1.0s!
Started 'install'
begin streaming logs
received log chunk of 20 bytes
gem install bundler

received log chunk of 53 bytes
Successfully installed bundler-2.1.4
1 gem installed

received log chunk of 15 bytes
bundle install

received log chunk of 245 bytes
The git source `git://github.com/excpt/moments.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.

received log chunk of 54 bytes
You must use Bundler 2 or greater with this lockfile.

received log chunk of 16 bytes

Exit status: 20
command failed
'install' failed in 1.1s!
Started 'rubocop'
begin streaming logs
received log chunk of 65 bytes
Uploading 0 artifacts for /tmp/cirrus-ci/working-dir/rubocop.json
command succeeded
'rubocop' succeeded in 0.0s!
container exited with <nil> error and exit code 0
cleaning up container 08a0722b78b85512e637e6c3a8ba4ef5acf1a6a81555ad9548c013fabe86792a
Error: build failed: task rubocop (3) failed
'rubocop' failed in 7.2s!
2020/09/10 01:08:22 build failed: task rubocop (3) failed

~/Projects/alexwayfer.name ((a44ab0a4…)|✚1)
> git diff
diff --git a/.cirrus.yml b/.cirrus.yml
index eb4b194..56e5fba 100644
--- a/.cirrus.yml
+++ b/.cirrus.yml
@@ -61,7 +61,7 @@ rubocop_task:
     image: ruby:latest
   <<: *bundle_cache
 
-  lint_script: toys rubocop --format=json --out=rubocop.json
+  lint_script: toys rubocop --format=json
 
   always:
     rubocop_artifacts
```

I even don't see any JSON output, so… what I should do?

**Comment by edigaryev** [comment]
> I even don't see any JSON output, so… what I should do?

```
You must use Bundler 2 or greater with this lockfile.

received log chunk of 16 bytes

Exit status: 20
command failed
'install' failed in 1.1s!
```

I see that you're running from `a44ab0a4`, but perhaps there are still some dirty files in the repository? Bundler's exit code 20 (https://github.com/rubygems/bundler/blob/a400c5ed9eca82598a76f9818a1bf7129515a2a0/lib/bundler.rb#L70) is somewhat consistent with the `You must use Bundler 2 or greater with this lockfile.` message above.

**Comment by AlexWayfer** [comment]
> but perhaps there are still some dirty files in the repository?

Only for output:

```
~/Projects/alexwayfer.name ((a44ab0a4…)|✚1)
> git diff
diff --git a/.cirrus.yml b/.cirrus.yml
index eb4b194..56e5fba 100644
--- a/.cirrus.yml
+++ b/.cirrus.yml
@@ -61,7 +61,7 @@ rubocop_task:
     image: ruby:latest
   <<: *bundle_cache
 
-  lint_script: toys rubocop --format=json --out=rubocop.json
+  lint_script: toys rubocop --format=json
 
   always:
     rubocop_artifacts:
~/Projects/alexwayfer.name ((a44ab0a4…)|✚1)
```

> `You must use Bundler 2 or greater with this lockfile.`

```
> bundle -v
Bundler version 2.1.4
```

What's wrong?

**Comment by edigaryev** [comment]
I wonder if running `docker pull ruby:latest` before `cirrus run -v rubocop` would help?

**Comment by AlexWayfer** [comment]
> I wonder if running `docker pull ruby:latest` before `cirrus run -v rubocop` would help?

Yes, thank you, wonderful!

Now I have such output:

```
Started 'lint'
begin streaming logs
received log chunk of 27 bytes
toys rubocop --format=json

received log chunk of 58 bytes
[2020-09-10 21:46:07   ANY]  ["rubocop", "--format=json"]

received log chunk of 1384 bytes
{"metadata":{"rubocop_version":"0.90.0","ruby_engine":"ruby","ruby_version":"2.7.1","ruby_patchlevel":"83","ruby_platform":"x86_64-linux"},"files":[{"path":".toys.rb","offenses":[]},{"path":"Gemfile","offenses":[]},{"path":"exe/_bundler_setup.rb","offenses":[]},{"path":"exe/compile.rb","offenses":[]},{"path":"exe/compile/_base_command.rb","offenses":[{"severity":"convention","message":"Consider merging nested conditions into outer `unless` conditions.","cop_name":"Style/SoleNestedConditional","corrected":false,"correctable":false,"location":{"start_line":22,"start_column":10,"last_line":22,"last_column":15,"length":6,"line":22,"column":10}}]},{"path":"exe/compile/all_command.rb","offenses":[]},{"path":"exe/compile/assets_command.rb","offenses":[]},{"path":"exe/compile/data.rb","offenses":[]},{"path":"exe/compile/pages_command.rb","offenses":[{"severity":"warning","message":"Useless method definition detected.","cop_name":"Lint/UselessMethodDefinition","corrected":false,"correctable":true,"location":{"start_line":89,"start_column":4,"last_line":91,"last_column":6,"length":88,"line":89,"column":4}}]},{"path":"exe/compile/pdf_command.rb","offenses":[]},{"path":"exe/compile/view_object.rb","offenses":[]},{"path":"exe/deploy.rb","offenses":[]},{"path":"extra/deploy_api.rb","offenses":[]}],"summary":{"offense_count":2,"target_file_count":13,"inspected_file_count":13}}
command failed
'lint' failed in 1.5s!
Started 'rubocop'
begin streaming logs
received log chunk of 65 bytes
Uploading 0 artifacts for /tmp/cirrus-ci/working-dir/rubocop.json
command succeeded
'rubocop' succeeded in 0.0s!
container exited with <nil> error and exit code 0
cleaning up container d9214ea9414ffa0e7603f77c59df62b75f86e33a468292e3c8e570270580ed7d
Error: build failed: task rubocop (3) failed
2020/09/11 00:46:09 build failed: task rubocop (3) failed
'rubocop' failed in 22s!
```

OK, this is strange, I think it's not `cirrus-cli`s issue, so let's close the discussion. I don't know why is it so (different outputs), but if an original issue has been resolved — we're fine.

**Pull request merged**
